name: Balatro
version: '${version}'
main: cn.quotidietium.balatro.BalatroPlugin
api-version: '26.2'
author: ZTF3
authors: [ZTF3, Dalict]
description: Brings the poker deck-building roguelike of the Steam game Balatro into Minecraft.
softdepend: [Vault]
commands:
  balatro:
    description: Balatro main command
    usage: /balatro help [page] | gui | play [deck] [stake] [challenge] [seed] | playcard | disc | shop | buy | buybag | buyvoucher | reroll | next | go | skip | cons | use | packs | pick | skipack | sellj | sellc | status | endless | top | version | quit
    aliases: [blt, joker]
permissions:
  balatro.play:
    description: Allows starting and quitting a Balatro run
    default: true
  balatro.admin:
    description: Allows administrative actions such as reloading the config
    default: op
